# Generated by Django 4.0.1 on 2022-02-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description_product_image_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out Of Stock')], default='IN_STOCK', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
            preserve_default=False,
        ),
    ]
