# Generated by Django 4.0.1 on 2022-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_external_id_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_byn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
