# Generated by Django 4.0.1 on 2022-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_price_byn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_byn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
