# Generated by Django 4.0.1 on 2022-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_price_byn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_byn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
